#pragma once
#ifndef POINT_POSITION_TO_TRIANGLE
#define POINT_POSITION_TO_TRIANGLE

#endif // POINT_POSITION_TO_TRIANGLE

enum POINT_POSITION_TO_TRIANGLE {
    ON_EDGE = 0,
    INSIDE = 1,
    OUTSIDE = 2
};
